language: node_js
node_js:
  - "10"
install:
  - npm install -g vuepress
branches:
  only:
  - master
script:
  - npm install
  - npm run docs:build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: master
    on:
        branch: master